[workspace]
members = [
    "sbbw",
    "sbbw-exec",
    "sbbw-widget-conf",
    "sbbw-widget",
]

[profile.release]
opt-level = "z" # Optimize for size.
# strip = true    # Automatically strip symbols from the binary.
lto = true
