allow-branch = ["main", "dev", "feature/*"]
sign-commit = true
sign-tag = true
push-remote = "origin"
release = true
publish = false
pre-release-commit-message = "chore: Release {{crate_name}} version {{version}}"
pre-release-replacements = []
tag-message = "chore: Release {{crate_name}} version {{version}}"
tag-name = "v{{version}}{{prefix}}"
tag = true
