name: Deploy Wiki

on:
  push:
    paths:
      # Trigger only when node api directory changes
      - 'sbbw_node/**'
    branches:
      # And only on master branch
      - main

jobs:
  deploy-wiki:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - uses: c-hive/gha-yarn-cache@v2
    - name: Install NodeJs dependencies
      run: yarn install --cwd sbbw_node
    - name: Build Docs
      run: yarn --cwd sbbw_node generate-docs

    - name: Push Wiki Changes
      uses: Andrew-Chen-Wang/github-wiki-action@v3
      env:
        WIKI_DIR: sbbw_node/docs
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GH_MAIL: ${{ secrets.YOUR_EMAIL }}
        GH_NAME: ${{ github.repository_owner }}
